// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udvjomufeklnjfpakxlq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkdmpvbXVmZWtsbmpmcGFreGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NTE3MjIsImV4cCI6MjA1ODEyNzcyMn0.BsbFqP9TuGPhRoSS-mhyW2VeOYUGX-QacY2XCOSOZJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);